### ISSUE TITLE
Specific SQL version required?

### ISSUE THREAD

**Issue by giriputraa** [bakwc/mysql_ch_replicator#20]
Hey, the project looks interesting but I unfortunately failed to run it. This is the error message I got from the debug logs. Any help appreciated.

```
Traceback (most recent call last):
  File "/root/.local/share/pipx/venvs/mysql-ch-replicator/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 706, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'key > 'None' ORDER BY key LIMIT 50000' at line 1
```

**Comment by giriputraa** [comment]
To clarify
MySQL Version: 8.0.31-google
Clickhouse Version: 24.9.2.42

**Comment by bakwc** [comment]
Could you please provide more information about table structure, especially a primary key type?

**Comment by bakwc** [comment]
Yeah, currently primary key is required for replication and for ClickHouse MergeTree engine. Will add explicit check for primary key check.
Thanks for feature suggestions, will add them later.

> if you support regex this should be possible already
For now it's a simple wildcard only, so only tables to use supported. Will add excluded_tables parameter.
