### ISSUE TITLE
mysql.connector.errors.DatabaseError: 1273 (HY000): Unknown collation: 'utf8mb4_0900_ai_ci'

### ISSUE THREAD

**Issue by rezashabrang** [bakwc/mysql_ch_replicator#25]
Does it support mariadb?

I get this error even though I changed the collation of the database.

**Comment by bakwc** [comment]
> Does it support mariadb?

Yes, it should work, investigating.

**Comment by bakwc** [comment]
Fixed in `0.0.32` version, please update and check if it helped.

**Comment by rezashabrang** [comment]
Thanks it worked👍🏻
