### ISSUE TITLE
Bigint not mapped to Int64

### ISSUE THREAD

**Issue by giriputraa** [bakwc/mysql_ch_replicator#28]
Source DB:
<img width="330" alt="Screenshot 2024-11-20 at 10 18 42 AM" src="https://github.com/user-attachments/assets/2d7634a4-5cd4-47f0-927d-59ec6c4a940f">

Clickhouse DB:
<img width="255" alt="Screenshot 2024-11-20 at 10 19 08 AM" src="https://github.com/user-attachments/assets/a593d46c-c7e2-4c0b-a8bb-56ad731ff29b">

I have checked the code and saw you have added support for bigint to be mapped to Int64, but for some reason it is mapped to Int32 instead. I'm using version 0.0.32. Thanks!

Edit:
converter.py line 126 
`if 'integer' in mysql_type or 'int(' in mysql_type:
            if is_unsigned:
                return 'UInt32'
            return 'Int32'`
Might this be the culprit? "bigint(20)" does contain "int(" in it causing the field to be mapped to Int32.

**Comment by giriputraa** [comment]
[PR](https://github.com/bakwc/mysql_ch_replicator/pull/29)

**Comment by bakwc** [comment]
Merged, published with release `0.0.33`
