### ISSUE TITLE
clickhouse final setting

### ISSUE THREAD

**Issue by yqmm666** [bakwc/mysql_ch_replicator#45]
<clickhouse>
    
    <profiles>
        <default>
            
            <final>1</final>
        </default>
    </profiles>
</clickhouse>

This configuration does not seem to be effective in the latest version of ClickHouse 24.11.1.2557

**Comment by bakwc** [comment]
Please double check that setting is applied. Execute this command in clickhouse and paste output:

`SELECT name, value, changed FROM system.settings WHERE name = 'final'`

Also please check you using the correct config file for clickhouse server.

**Comment by yqmm666** [comment]
> Please double check that setting is applied. Execute this command in clickhouse and paste output:
> 
> `SELECT name, value, changed FROM system.settings WHERE name = 'final'`
> 
> Also please check you using the correct config file for clickhouse server. You could also try to set it in `users.xml` file instead.

thanks. I put  it in the user.xml, that works
