### ISSUE TITLE
pivot table with no primary key could not migrate in clickhouse

### ISSUE THREAD

**Issue by johirulalam** [bakwc/mysql_ch_replicator#57]

**Comment by bakwc** [comment]
Clickhouse has a requirement to have a primary key on all tables, so we couldn't replicate tables without primary keys.
You could mark this tables as skipped.

**Comment by johirulalam** [comment]
> Clickhouse has a requirement to have a primary key on all tables, so we couldn't replicate tables without primary keys. You could mark this tables as skipped.

thank you
