### ISSUE TITLE
DB Replication error - KeyError: 'scrm_renewal_cstm'

### ISSUE THREAD

**Issue by simplecrm-github** [bakwc/mysql_ch_replicator#65]
Hi,

We are replicating only the below specific tables from mysql_ch_replication  but receiving the error **KeyError: '**scrm_renewal_cstm**'** which is not included in the table list. Could you help on priority?

**Table list in config.yaml**

tables: ['leads', 'leads_cstm', 'opportunities', 'opportunities_cstm', 'users', 'users_cstm', 'securitygroups', 'securitygroups_users', 'scrm_branch', 'scrm_branch_cstm', 'scrm_zone', 'scrm_zone_cstm', 'scrm_region', 'scrm_region_cstm', 'acl_roles', 'acl_roles_users', 'scrm_zone_scrm_branch_1_c', 'scrm_region_scrm_branch_1_c', 'scrm_region_scrm_zone_1_c', 'scrm_sales_lead', 'scrm_sales_lead_cstm', 'scrm_user_history', 'scrm_campaigns', 'scrm_campaigns_cstm', 'scrm_sales_campaign', 'scrm_sales_campaign_cstm','opportunities_scrm_conversion_details_1_c','scrm_conversion_details']

**Error**:

[dbrepl insurancecrmdb 2024-12-26 06:20:57,940     INFO] launched db_replicator
[dbrepl insurancecrmdb 2024-12-26 06:20:57,966     INFO] running realtime replication from the position: ('binlog.000013', 319058235)
[dbrepl insurancecrmdb 2024-12-26 06:21:01,756     INFO] set position to /binlog/insurancecrmdb/348.bin
[dbrepl insurancecrmdb 2024-12-26 06:21:01,765     INFO] found transaction ('binlog.000013', 319058235) inside /binlog/insurancecrmdb/348.bin
[dbrepl insurancecrmdb 2024-12-26 06:21:01,786    ERROR] unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/mysql_ch_replicator/db_replicator.py", line 178, in run
    self.run_realtime_replication()
  File "/usr/local/lib/python3.11/site-packages/mysql_ch_replicator/db_replicator.py", line 379, in run_realtime_replication
    self.handle_event(event)
  File "/usr/local/lib/python3.11/site-packages/mysql_ch_replicator/db_replicator.py", line 401, in handle_event
    event_handlers[event.event_type](event)
  File "/usr/local/lib/python3.11/site-packages/mysql_ch_replicator/db_replicator.py", line 480, in handle_query_event
    self.handle_alter_query(query, event.db_name)
  File "/usr/local/lib/python3.11/site-packages/mysql_ch_replicator/db_replicator.py", line 488, in handle_alter_query
    self.converter.convert_alter_query(query, db_name)
  File "/usr/local/lib/python3.11/site-packages/mysql_ch_replicator/converter.py", line 376, in convert_alter_query
    self.__convert_alter_table_add_column(db_name, table_name, tokens)
  File "/usr/local/lib/python3.11/site-packages/mysql_ch_replicator/converter.py", line 420, in __convert_alter_table_add_column
    table_structure = self.db_replicator.state.tables_structure[table_name]
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
**KeyError: 'scrm_renewal_cstm'**

**Comment by simplecrm-github** [comment]
FYI:

We are using mysql-ch-replicator   version as 0.0.46

**Comment by bakwc** [comment]
Merged a fix, please update to version `0.0.49` and check if it helped

**Comment by simplecrm-github** [comment]
Updated to the version 0.0.49. now the issue is fixed. Thanks.



I am currently running real-time replication using the following command:

**mysql_ch_replicator --config /clickhouse/settings.yaml run_all**  

Now, I would like to include a few more tables in the settings.yaml file. Do I need to stop this command and restart it for the replication to include the newly added tables?"

**Comment by bakwc** [comment]
You also need to remove a data. Please check `settings.yaml` file, find `binlog_replicator` -> `data_dir` parameter. You need to:
1) Stop running `mysql_ch_replicator --config /clickhouse/settings.yaml run_all`
2) Remove that directory
3) Start `mysql_ch_replicator --config /clickhouse/settings.yaml run_all`

**Comment by simplecrm-github** [comment]
Thank You!
