### ISSUE TITLE
Replicate only partial table

### ISSUE THREAD

**Issue by spartan** [bakwc/mysql_ch_replicator#7]
Hello,

Is there a way to replicate only a part of a table?
For example, to replicate using a condition like `WHERE id < 10000`.

Thank you!

**Comment by bakwc** [comment]
Could you please provide more details about your use-case (what are you trying to achieve)?
1) Do you need this filter only for initial replication, or for continuous replication too?
2) Are you trying to just copy data once (for some test purposes) or you want to make some sort of sharding (eg one part goes to 1 ch server, other goes to another etc.)?
3) Do you need to filter only by ID or some other columns too?

**Comment by bakwc** [comment]
For now closing, will reopen when get more details about requirements
